apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
spec:
  selector:
    matchLabels:
      app: audit-service
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: octopub-audits
          image: octopussamples/octopub-audit-microservice
          ports:
            - name: http
              containerPort: 10000
          resources:
            limits:
              memory: 1024Mi
              cpu: "500m"
            requests:
              memory: 512Mi
              cpu: "250m"
          env:
          - name: DATABASE_HOSTNAME
            value: mysql.database.svc.cluster.local
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: octopub
          - name: DATABASE_USERNAME
            value: root
          - name: DATABASE_PASSWORD
            value: "password goes here"
          - name: MIGRATE_AT_START
            value: "true"